# Generated by Django 6.0.4 on 2026-05-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('skills', models.JSONField()),
                ('experience', models.FloatField()),
                ('location', models.CharField(max_length=300)),
                ('description', models.TextField()),
            ],
        ),
    ]
