# Generated by Django 6.0.4 on 2026-05-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
